// Fonts
import { fontSans, fontMono } from "./fonts"
// Global Css
import "./globals.css"
// 
import { cn } from "@/lib/utils"
// Components
import { Header } from "@/components"
// Meta Data
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    }
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("font-sans font-normal scroll-smooth", fontSans.variable, fontMono.variable)}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}